version: '3.1'
services:
  nats-streaming:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats-streaming.conf:/etc/nats-streaming.conf
  postgres:
    image: postgres
    ports:
      - "5500:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rec
    volumes:
      - ./internal/models/model.sql:/docker-entrypoint-initdb.d/init.sql
